### PR TITLE
Use shared memory to determine results of forked test runs

### LINKED ISSUE #48: Don't use exit codes for replayed take-over test cases
If we replay a take-over test case natively, and the forked take-over test case _soft_ fails, we will fail to detect the soft failure in the parent process.

This is because we are communicating failure via exit codes, but soft failures only manifest via global variable updates in the child process. Really, for take-over tests, the "test case" is just some binary, which might correctly have a nonzero exit that we _don't_ want to call a "failure".

Instead, we should do something like sharing memory between the child and parent process, and inspecting the child's shared memory when it exits.

### PR DESCRIPTION
**Pull request by ranweiler**
Closes #48.

### CODE REVIEW

**Comment by ranweiler** [comment]
Note that we _don't_ currently use a shared memory approach for _unit test_ replays; we still rely on exit codes to report non-crashing run results. That's okay for that situation, since we have extra information about the unit tests— we don't typically expect users to manually `exit()` from those, since their program is expressed using an API we have defined. If they _do_ manually `exit()` from a unit test, the exit codes they are most likely to use would match our exit code handling assumptions anyway.

For the sake of simplicity, we should unify our handling of forked test runs, but we can do that in another PR. It is much less important in the unit test case than in the take-over case, where it was causing mis-reporting, and didn't make sense in general (a manually-instrumented user program might non-erroneously return a nonzero value).

File: src/include/deepstate/DeepState.h [hunk 1]
```diff
@@ -350,11 +358,11 @@ extern void DeepState_Begin(struct DeepState_TestInfo *info);
 /* Return the first test case to run. */
 extern struct DeepState_TestInfo *DeepState_FirstTest(void);
 
-/* Returns 1 if a failure was caught, otherwise 0. */
-extern int DeepState_CatchFail(void);
+/* Returns `true` if a failure was caught for the current test case. */
+extern bool DeepState_CatchFail(void);
```
Comment (pgoodman) [inline src/include/deepstate/DeepState.h]: I have this as `int` because it's C, does changing to `bool` reduce the portability of the code?

Comment (ranweiler) [reply src/include/deepstate/DeepState.h]: I don't think it commits us to any non-portability we haven't already taken on.

IIUC: `stdbool.h` is part of C99 (we are using `bool` in one other function, I think). But fixed-size types like `uint8_t` (`stdint.h`/`inttypes.h`) are _also_ properly part of C99, and we really want (and were already using) those.
